# Generated by Django 2.2 on 2019-06-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='文件名')),
                ('is_show', models.BooleanField(default=True, verbose_name='展示')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='上传时间')),
                ('change_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('folder_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='files.Folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
